services:
  - type: web
    name: gov-budget-api
    env: docker
    plan: free
    region: oregon
    branch: deploy/render
    dockerfilePath: ./Dockerfile
    rootDir: /
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Gov Budget API
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://gov-budget-api.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
